Howtoplay
townteki/townsquare-client pull request #72
Opened 2021-07-21 19:11 UTC by AaronSchnabel

Updated the home page background image with one that has the Pinnacle and Pinebox logos, updated How To Play to remove more Iron Throne references and put in specific card interactions for DTO. Also added information to the About page.

2021-08-02 15:14 UTC, mmeldo requested changes
I would also add a new section after `Specific Card Interactions`. It would be named `Using of Unscripted Cards`.
There, it would be described how to use them:
- type `/use` command and select card, or drag action card into the 'being played' pile
- use other chat commands or other ways to perform card ability
- if done, click on the "Done" button in the prompt which will move the order

If you want I can put it into the PR.

2021-08-02 15:14 UTC, mmeldo commented on pages/About.jsx
> +                    <h2>Patreon</h2>
Not sure yet about this as it is not yet decided how the subscriptions will look like. I would put it here once it is decided.

2021-08-02 15:14 UTC, mmeldo commented on pages/HowToPlay.jsx
> +                                <li><a href='#johnnybrocklehurst'>Johnny Brocklehurst</a></li>
Let's make this as one list item.
```suggestion
                                <li><a href='#margesandjohnny'>Old Marge's Manor and Johnny Brocklehurst</a></li>
```

2021-08-02 15:14 UTC, mmeldo commented on pages/HowToPlay.jsx
> +                        </div>
Let's make this as one section
```suggestion
                            <h4 className='htp-subtitle' id='margesandjohnny'>Old Marge's Manor and Johnny Brocklehurst</h4>
                            <p><a href='https://dtdb.co/en/card/12012' target='blank'>Old Marge's Manor</a>'s and <a href='https://dtdb.co/en/card/19017' target='blank'>Johnny Brocklehurst</a>'s React ability must be triggered as a normal Noon action instead of a React. When you want to use it, click the card and choose "Use Ability" on the card menu</p>
                        </div>
```

2021-08-02 15:14 UTC, mmeldo commented on less/site.less
> +  background-image: url("/img/background logoed.webp");
I would rather use the same background and have the logo as a separate image with transparent canvas which can be put in the corner. This way we do not have to change the `background-size` because the "contain" value put it in the middle and in widescreens cause big black columns at the sides.

2021-08-06 07:40 UTC, mmeldo commented
> I would also add a new section after `Specific Card Interactions`. It would be named `Using of Unscripted Cards`.
> There, it would be described how to use them:
> 
> * type `/use` command and select card, or drag action card into the 'being played' pile
> * use other chat commands or other ways to perform card ability
> * if done, click on the "Done" button in the prompt which will move the order
> 
> If you want I can put it into the PR.

I have put this to the PR.

2021-08-11 16:47 UTC, AaronSchnabel commented on less/site.less
> +  background-image: url("/img/background logoed.webp");
I've changed the background back and added a new file (bglogo.webp) to use as that secondary image. I added a class for it in site.less but haven't yet figured out how to actually add it to the site so that it gets overlaid on the background.

2021-08-11 16:48 UTC, AaronSchnabel commented on pages/About.jsx
> +                    <h2>Patreon</h2>
I put this in as a placeholder until those things are figured out. I figured we'd have Lapp or Alex look at it and approve/suggest changes for this section for now.

2021-08-11 17:34 UTC, AaronSchnabel commented on less/site.less
> +  background-image: url("/img/background logoed.webp");
Never mind, I figured out how to overlay the logo image on the background. I adjusted size, position, colors, and the shadowbox to make it look better and be in a visible position on smaller screen resolutions.

2021-08-16 21:03 UTC, mmeldo approved these changes

2021-08-16 21:04 UTC, merged